name: PR Build and Deploy

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install angular cli
      run: npm install --location=global @angular/cli

    - name: npm install
      run: npm install

    - name: Build
      run: ng build

    - name: Run tests
      run: ng test --no-watch --karma-config karma.workflow.conf.js --code-coverage

    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: "testresults/junit/unit-test-result.xml"

    - name: Publish code coverage
      uses: 5monkeys/cobertura-action@master
      with:
        path: coverage\the-site\cobertura-coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 90

    - name: Move static apps config file
      run: cp staticwebapp.config.json dist/the-site/staticwebapp.config.json

    - name: Upload frontend artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: app-artifacts
        path: dist/the-site

  deploy-pr:
    runs-on: ubuntu-latest
    name: Deploy to PR environment
    needs: build-and-test

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
          path: app-artifacts

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: app-artifacts
          ## api_location: ${{ env.API_LOCATION }}
          skip_app_build: true
          ###### End of Repository/Build Configurations ######