name: Deploy web app to Azure Static Web Apps Production

on:
  release:
    types: released

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
      with:
        source_workflow: "PR_close.yml"